#############################################################################
# Makefile for building: robhmi
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  robhmi.pro
# Template: subdirs
# Command: D:\Qt\Qt5.3.2\5.3\mingw482_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile robhmi.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.3.2\5.3\mingw482_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-DataManage \
		sub-robDecodePrg \
		sub-FileAndDirOperate \
		sub-DataProcess \
		sub-ParaSet \
		sub-KeyWorld \
		sub-RobAlarm \
		sub-robUI \
		sub-hmi


sub-DataManage-qmake_all:  FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd DataManage\ && $(MAKE) -f Makefile qmake_all
sub-DataManage: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-DataManage-make_first-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DataManage-make_first: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DataManage-all-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DataManage-all: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DataManage-clean-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DataManage-clean: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DataManage-distclean-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DataManage-distclean: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DataManage-install_subtargets-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DataManage-install_subtargets: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DataManage-uninstall_subtargets-ordered: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-DataManage-uninstall_subtargets: FORCE
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-robDecodePrg-qmake_all: sub-DataManage-qmake_all FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd robDecodePrg\ && $(MAKE) -f Makefile qmake_all
sub-robDecodePrg: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-robDecodePrg-make_first-ordered: sub-DataManage-make_first-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-robDecodePrg-make_first: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-robDecodePrg-all-ordered: sub-DataManage-all-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-robDecodePrg-all: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-robDecodePrg-clean-ordered: sub-DataManage-clean-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-robDecodePrg-clean: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-robDecodePrg-distclean-ordered: sub-DataManage-distclean-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-robDecodePrg-distclean: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-robDecodePrg-install_subtargets-ordered: sub-DataManage-install_subtargets-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-robDecodePrg-install_subtargets: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-robDecodePrg-uninstall_subtargets-ordered: sub-DataManage-uninstall_subtargets-ordered  FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-robDecodePrg-uninstall_subtargets: FORCE
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-FileAndDirOperate-qmake_all: sub-robDecodePrg-qmake_all FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd FileAndDirOperate\ && $(MAKE) -f Makefile qmake_all
sub-FileAndDirOperate: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-FileAndDirOperate-make_first-ordered: sub-robDecodePrg-make_first-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-FileAndDirOperate-make_first: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-FileAndDirOperate-all-ordered: sub-robDecodePrg-all-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-FileAndDirOperate-all: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-FileAndDirOperate-clean-ordered: sub-robDecodePrg-clean-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-FileAndDirOperate-clean: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-FileAndDirOperate-distclean-ordered: sub-robDecodePrg-distclean-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-FileAndDirOperate-distclean: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-FileAndDirOperate-install_subtargets-ordered: sub-robDecodePrg-install_subtargets-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-FileAndDirOperate-install_subtargets: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-FileAndDirOperate-uninstall_subtargets-ordered: sub-robDecodePrg-uninstall_subtargets-ordered  FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-FileAndDirOperate-uninstall_subtargets: FORCE
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-DataProcess-qmake_all: sub-FileAndDirOperate-qmake_all FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd DataProcess\ && $(MAKE) -f Makefile qmake_all
sub-DataProcess: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-DataProcess-make_first-ordered: sub-FileAndDirOperate-make_first-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DataProcess-make_first: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-DataProcess-all-ordered: sub-FileAndDirOperate-all-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DataProcess-all: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-DataProcess-clean-ordered: sub-FileAndDirOperate-clean-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DataProcess-clean: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-DataProcess-distclean-ordered: sub-FileAndDirOperate-distclean-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DataProcess-distclean: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-DataProcess-install_subtargets-ordered: sub-FileAndDirOperate-install_subtargets-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DataProcess-install_subtargets: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-DataProcess-uninstall_subtargets-ordered: sub-FileAndDirOperate-uninstall_subtargets-ordered  FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-DataProcess-uninstall_subtargets: FORCE
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ParaSet-qmake_all: sub-DataProcess-qmake_all FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd ParaSet\ && $(MAKE) -f Makefile qmake_all
sub-ParaSet: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ParaSet-make_first-ordered: sub-DataProcess-make_first-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ParaSet-make_first: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ParaSet-all-ordered: sub-DataProcess-all-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ParaSet-all: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ParaSet-clean-ordered: sub-DataProcess-clean-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ParaSet-clean: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ParaSet-distclean-ordered: sub-DataProcess-distclean-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ParaSet-distclean: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ParaSet-install_subtargets-ordered: sub-DataProcess-install_subtargets-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ParaSet-install_subtargets: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ParaSet-uninstall_subtargets-ordered: sub-DataProcess-uninstall_subtargets-ordered  FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ParaSet-uninstall_subtargets: FORCE
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-KeyWorld-qmake_all: sub-ParaSet-qmake_all FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd KeyWorld\ && $(MAKE) -f Makefile qmake_all
sub-KeyWorld: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-KeyWorld-make_first-ordered: sub-ParaSet-make_first-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-KeyWorld-make_first: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-KeyWorld-all-ordered: sub-ParaSet-all-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-KeyWorld-all: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-KeyWorld-clean-ordered: sub-ParaSet-clean-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-KeyWorld-clean: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-KeyWorld-distclean-ordered: sub-ParaSet-distclean-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-KeyWorld-distclean: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-KeyWorld-install_subtargets-ordered: sub-ParaSet-install_subtargets-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-KeyWorld-install_subtargets: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-KeyWorld-uninstall_subtargets-ordered: sub-ParaSet-uninstall_subtargets-ordered  FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-KeyWorld-uninstall_subtargets: FORCE
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-RobAlarm-qmake_all: sub-KeyWorld-qmake_all FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd RobAlarm\ && $(MAKE) -f Makefile qmake_all
sub-RobAlarm: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-RobAlarm-make_first-ordered: sub-KeyWorld-make_first-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-RobAlarm-make_first: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-RobAlarm-all-ordered: sub-KeyWorld-all-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-RobAlarm-all: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-RobAlarm-clean-ordered: sub-KeyWorld-clean-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-RobAlarm-clean: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-RobAlarm-distclean-ordered: sub-KeyWorld-distclean-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-RobAlarm-distclean: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-RobAlarm-install_subtargets-ordered: sub-KeyWorld-install_subtargets-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-RobAlarm-install_subtargets: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-RobAlarm-uninstall_subtargets-ordered: sub-KeyWorld-uninstall_subtargets-ordered  FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-RobAlarm-uninstall_subtargets: FORCE
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-robUI-qmake_all: sub-RobAlarm-qmake_all FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd robUI\ && $(MAKE) -f Makefile qmake_all
sub-robUI: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-robUI-make_first-ordered: sub-RobAlarm-make_first-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-robUI-make_first: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-robUI-all-ordered: sub-RobAlarm-all-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-robUI-all: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-robUI-clean-ordered: sub-RobAlarm-clean-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-robUI-clean: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-robUI-distclean-ordered: sub-RobAlarm-distclean-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-robUI-distclean: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-robUI-install_subtargets-ordered: sub-RobAlarm-install_subtargets-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-robUI-install_subtargets: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-robUI-uninstall_subtargets-ordered: sub-RobAlarm-uninstall_subtargets-ordered  FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-robUI-uninstall_subtargets: FORCE
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-hmi-qmake_all: sub-robUI-qmake_all FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd hmi\ && $(MAKE) -f Makefile qmake_all
sub-hmi: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-hmi-make_first-ordered: sub-robUI-make_first-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-hmi-make_first: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-hmi-all-ordered: sub-robUI-all-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-hmi-all: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-hmi-clean-ordered: sub-robUI-clean-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-hmi-clean: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-hmi-distclean-ordered: sub-robUI-distclean-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-hmi-distclean: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-hmi-install_subtargets-ordered: sub-robUI-install_subtargets-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-hmi-install_subtargets: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-hmi-uninstall_subtargets-ordered: sub-robUI-uninstall_subtargets-ordered  FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-hmi-uninstall_subtargets: FORCE
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: robhmi.pro D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/qdevice.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/device_config.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/common/shell-win32.conf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/qconfig.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_post.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/yacc.prf \
		D:/Qt/Qt5.3.2/5.3/mingw482_32/mkspecs/features/lex.prf \
		robhmi.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile robhmi.pro
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\spec_pre.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\qdevice.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\device_config.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\common\shell-win32.conf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\qconfig.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_clucene_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_core.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_help.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_network.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_script.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\qt_functions.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\qt_config.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\win32\qt_config.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\win32-g++\qmake.conf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\spec_post.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\exclusive_builds.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\default_pre.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\win32\default_pre.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\resolve_config.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\default_post.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\win32\rtti.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\precompile_header.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\warn_on.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\win32\windows.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\testcase_targets.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\exceptions.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\yacc.prf:
D:\Qt\Qt5.3.2\5.3\mingw482_32\mkspecs\features\lex.prf:
robhmi.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile robhmi.pro

qmake_all: sub-DataManage-qmake_all sub-robDecodePrg-qmake_all sub-FileAndDirOperate-qmake_all sub-DataProcess-qmake_all sub-ParaSet-qmake_all sub-KeyWorld-qmake_all sub-RobAlarm-qmake_all sub-robUI-qmake_all sub-hmi-qmake_all FORCE

make_first: sub-DataManage-make_first-ordered sub-robDecodePrg-make_first-ordered sub-FileAndDirOperate-make_first-ordered sub-DataProcess-make_first-ordered sub-ParaSet-make_first-ordered sub-KeyWorld-make_first-ordered sub-RobAlarm-make_first-ordered sub-robUI-make_first-ordered sub-hmi-make_first-ordered FORCE
all: sub-DataManage-all-ordered sub-robDecodePrg-all-ordered sub-FileAndDirOperate-all-ordered sub-DataProcess-all-ordered sub-ParaSet-all-ordered sub-KeyWorld-all-ordered sub-RobAlarm-all-ordered sub-robUI-all-ordered sub-hmi-all-ordered FORCE
clean: sub-DataManage-clean-ordered sub-robDecodePrg-clean-ordered sub-FileAndDirOperate-clean-ordered sub-DataProcess-clean-ordered sub-ParaSet-clean-ordered sub-KeyWorld-clean-ordered sub-RobAlarm-clean-ordered sub-robUI-clean-ordered sub-hmi-clean-ordered FORCE
distclean: sub-DataManage-distclean-ordered sub-robDecodePrg-distclean-ordered sub-FileAndDirOperate-distclean-ordered sub-DataProcess-distclean-ordered sub-ParaSet-distclean-ordered sub-KeyWorld-distclean-ordered sub-RobAlarm-distclean-ordered sub-robUI-distclean-ordered sub-hmi-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-DataManage-install_subtargets-ordered sub-robDecodePrg-install_subtargets-ordered sub-FileAndDirOperate-install_subtargets-ordered sub-DataProcess-install_subtargets-ordered sub-ParaSet-install_subtargets-ordered sub-KeyWorld-install_subtargets-ordered sub-RobAlarm-install_subtargets-ordered sub-robUI-install_subtargets-ordered sub-hmi-install_subtargets-ordered FORCE
uninstall_subtargets: sub-DataManage-uninstall_subtargets-ordered sub-robDecodePrg-uninstall_subtargets-ordered sub-FileAndDirOperate-uninstall_subtargets-ordered sub-DataProcess-uninstall_subtargets-ordered sub-ParaSet-uninstall_subtargets-ordered sub-KeyWorld-uninstall_subtargets-ordered sub-RobAlarm-uninstall_subtargets-ordered sub-robUI-uninstall_subtargets-ordered sub-hmi-uninstall_subtargets-ordered FORCE

sub-DataManage-debug_ordered:
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-robDecodePrg-debug_ordered: sub-DataManage-debug_ordered 
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-FileAndDirOperate-debug_ordered: sub-robDecodePrg-debug_ordered 
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-DataProcess-debug_ordered: sub-FileAndDirOperate-debug_ordered 
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-ParaSet-debug_ordered: sub-DataProcess-debug_ordered 
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-KeyWorld-debug_ordered: sub-ParaSet-debug_ordered 
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-RobAlarm-debug_ordered: sub-KeyWorld-debug_ordered 
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-robUI-debug_ordered: sub-RobAlarm-debug_ordered 
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-hmi-debug_ordered: sub-robUI-debug_ordered 
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-DataManage-debug_ordered sub-robDecodePrg-debug_ordered sub-FileAndDirOperate-debug_ordered sub-DataProcess-debug_ordered sub-ParaSet-debug_ordered sub-KeyWorld-debug_ordered sub-RobAlarm-debug_ordered sub-robUI-debug_ordered sub-hmi-debug_ordered

sub-DataManage-release_ordered:
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-robDecodePrg-release_ordered: sub-DataManage-release_ordered 
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-FileAndDirOperate-release_ordered: sub-robDecodePrg-release_ordered 
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-DataProcess-release_ordered: sub-FileAndDirOperate-release_ordered 
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-ParaSet-release_ordered: sub-DataProcess-release_ordered 
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-KeyWorld-release_ordered: sub-ParaSet-release_ordered 
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-RobAlarm-release_ordered: sub-KeyWorld-release_ordered 
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-robUI-release_ordered: sub-RobAlarm-release_ordered 
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-hmi-release_ordered: sub-robUI-release_ordered 
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-DataManage-release_ordered sub-robDecodePrg-release_ordered sub-FileAndDirOperate-release_ordered sub-DataProcess-release_ordered sub-ParaSet-release_ordered sub-KeyWorld-release_ordered sub-RobAlarm-release_ordered sub-robUI-release_ordered sub-hmi-release_ordered

sub-DataManage-check_ordered:
	@if not exist DataManage\ mkdir DataManage\ & if not exist DataManage\ exit 1
	cd DataManage\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataManage\DataManage.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-robDecodePrg-check_ordered: sub-DataManage-check_ordered 
	@if not exist robDecodePrg\ mkdir robDecodePrg\ & if not exist robDecodePrg\ exit 1
	cd robDecodePrg\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robDecodePrg\robDecodePrg.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-FileAndDirOperate-check_ordered: sub-robDecodePrg-check_ordered 
	@if not exist FileAndDirOperate\ mkdir FileAndDirOperate\ & if not exist FileAndDirOperate\ exit 1
	cd FileAndDirOperate\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\FileAndDirOperate\FileAndDirOperate.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-DataProcess-check_ordered: sub-FileAndDirOperate-check_ordered 
	@if not exist DataProcess\ mkdir DataProcess\ & if not exist DataProcess\ exit 1
	cd DataProcess\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\DataProcess\DataProcess.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ParaSet-check_ordered: sub-DataProcess-check_ordered 
	@if not exist ParaSet\ mkdir ParaSet\ & if not exist ParaSet\ exit 1
	cd ParaSet\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\ParaSet\ParaSet.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-KeyWorld-check_ordered: sub-ParaSet-check_ordered 
	@if not exist KeyWorld\ mkdir KeyWorld\ & if not exist KeyWorld\ exit 1
	cd KeyWorld\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\KeyWorld\KeyWorld.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-RobAlarm-check_ordered: sub-KeyWorld-check_ordered 
	@if not exist RobAlarm\ mkdir RobAlarm\ & if not exist RobAlarm\ exit 1
	cd RobAlarm\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\RobAlarm\RobAlarm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-robUI-check_ordered: sub-RobAlarm-check_ordered 
	@if not exist robUI\ mkdir robUI\ & if not exist robUI\ exit 1
	cd robUI\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\robUI\robUI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-hmi-check_ordered: sub-robUI-check_ordered 
	@if not exist hmi\ mkdir hmi\ & if not exist hmi\ exit 1
	cd hmi\ && ( if not exist Makefile $(QMAKE) D:\workspace\Qt_Project\GSK_Robot\robhmi_1\robhmi\hmi\hmi.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-DataManage-check_ordered sub-robDecodePrg-check_ordered sub-FileAndDirOperate-check_ordered sub-DataProcess-check_ordered sub-ParaSet-check_ordered sub-KeyWorld-check_ordered sub-RobAlarm-check_ordered sub-robUI-check_ordered sub-hmi-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

