#ifndef ROBDECODEPRG_GLOBAL_H
#define ROBDECODEPRG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROBDECODEPRG_LIBRARY)
#  define ROBDECODEPRGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROBDECODEPRGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROBDECODEPRG_GLOBAL_H
